# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: start_slice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'start_slice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11start_slice.proto\x12\x05slice\"\xca\x01\n\x0cSliceRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_root\x18\x02 \x01(\t\x12\x11\n\tthreshold\x18\x03 \x01(\x02\x12\x12\n\nmin_length\x18\x04 \x01(\x05\x12\x14\n\x0cmin_interval\x18\x05 \x01(\x05\x12\x10\n\x08hop_size\x18\x06 \x01(\x05\x12\x14\n\x0cmax_sil_kept\x18\x07 \x01(\x05\x12\x0c\n\x04_max\x18\x08 \x01(\x05\x12\r\n\x05\x61lpha\x18\t \x01(\x02\x12\x0f\n\x07n_parts\x18\n \x01(\x05\"B\n\rStartResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12!\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x13.slice.KeyValuePair\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2G\n\x0cSliceService\x12\x37\n\nStartSlice\x12\x13.slice.SliceRequest\x1a\x14.slice.StartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'start_slice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SLICEREQUEST']._serialized_start=29
  _globals['_SLICEREQUEST']._serialized_end=231
  _globals['_STARTRESPONSE']._serialized_start=233
  _globals['_STARTRESPONSE']._serialized_end=299
  _globals['_KEYVALUEPAIR']._serialized_start=301
  _globals['_KEYVALUEPAIR']._serialized_end=343
  _globals['_SLICESERVICE']._serialized_start=345
  _globals['_SLICESERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
